# Generated by Django 4.2.20 on 2025-03-19 22:52

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=account.models.image_file_path
            ),
        ),
    ]
