# Generated by Django 4.2.18 on 2025-02-02 09:26

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=gallery.models.gallery_image_file_path,
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, verbose_name="قابل نمایش در سایت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=gallery.models.gallery_image_file_path,
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=gallery.models.medial_video_file_path,
                        verbose_name="فایل",
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(
                        default=False, verbose_name="قابل نمایش در سایت"
                    ),
                ),
            ],
        ),
    ]
