# Generated by Django 4.2.18 on 2025-02-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="fullName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
