# Generated by Django 4.2.18 on 2025-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0003_address_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(default="لطفا پر کنید", max_length=255),
        ),
    ]
