# Generated by Django 4.2.18 on 2025-02-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0005_alter_address_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
