# Generated by Django 4.2.20 on 2025-03-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0006_address_latitude_address_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="province.city",
            ),
        ),
    ]
