# Generated by Django 4.2.18 on 2025-02-02 09:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=85, verbose_name="عنوان")),
                ("slug", models.SlugField(max_length=170, verbose_name="اسلاگ")),
                (
                    "short_desc",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="توضیحات کوتاه",
                    ),
                ),
                (
                    "desc",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=72, null=True)),
                (
                    "image_title",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="blogs",
                        to="gallery.gallery",
                        verbose_name="تصویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
    ]
