# Generated by Django 4.2.18 on 2025-02-01 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("dashboard", "Dashboard")],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="monitoring__user_id_13fc75_idx",
                    ),
                    models.Index(
                        fields=["channel"], name="monitoring__channel_626ba0_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="monitoring__priorit_e26960_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="monitoring__timesta_2478f7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CodeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                            ("ACTION_LOG", "ActionLog"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("module", models.CharField(max_length=100)),
                ("method", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("cpu_usage", models.FloatField(blank=True, null=True)),
                ("memory_usage", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["level"], name="monitoring__level_2eda69_idx"),
                    models.Index(
                        fields=["module", "method"],
                        name="monitoring__module_6ab14a_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="monitoring__timesta_9ad46e_idx"
                    ),
                ],
            },
        ),
    ]
