# Generated by Django 4.2.18 on 2025-02-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0001_initial"),
        ("veterinary", "0002_veterinarian_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="veterinarians",
                to="province.province",
            ),
        ),
    ]
