# Generated by Django 4.2.18 on 2025-02-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0003_veterinarian_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="clinic_name",
            field=models.CharField(default="test", max_length=225),
            preserve_default=False,
        ),
    ]
