# Generated by Django 4.2.18 on 2025-02-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0004_veterinarian_clinic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="state",
            field=models.CharField(
                choices=[
                    ("B", "Busy"),
                    ("E", "Examination"),
                    ("F", "Free"),
                    ("R", "Responsible"),
                ],
                default="B",
                max_length=1,
            ),
        ),
    ]
