# Generated by Django 4.2.18 on 2025-02-04 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("veterinary", "0005_veterinarian_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=72)),
                (
                    "description",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="centers",
                        to="gallery.gallery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
