# Generated by Django 4.2.18 on 2025-02-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0006_medicalcenter"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="medical_center",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="veterinary.medicalcenter",
            ),
            preserve_default=False,
        ),
    ]
