# Generated by Django 4.2.18 on 2025-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0008_veterinarian_background_image_veterinarian_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rancher",
            name="veterinarians",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="ranchers",
                to="veterinary.veterinarian",
            ),
        ),
    ]
