# Generated by Django 4.2.18 on 2025-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0009_rancher_veterinarians"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rancher",
            name="veterinarians",
            field=models.ManyToManyField(
                related_name="ranchers", to="veterinary.veterinarian"
            ),
        ),
    ]
