# Generated by Django 4.2.18 on 2025-02-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0010_alter_rancher_veterinarians"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rancher",
            name="city",
        ),
        migrations.RemoveField(
            model_name="rancher",
            name="province",
        ),
    ]
