# Generated by Django 4.2.18 on 2025-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0012_animal"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="surgery",
            field=models.IntegerField(default=0),
        ),
    ]
