# Generated by Django 4.2.18 on 2025-03-07 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import veterinary.models.request_models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0013_veterinarian_experience_veterinarian_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "voice",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=veterinary.models.request_models.request_voice_file_path,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=veterinary.models.request_models.request_video_file_path,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("T", "Tell"), ("S", "SMS"), ("IP", "In-Person")],
                        default="IP",
                        max_length=2,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "rancher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="requests",
                        to="veterinary.rancher",
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="requests",
                        to="veterinary.veterinarian",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequestImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=veterinary.models.request_models.request_image_file_path
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="veterinary.request",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnimalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.PositiveIntegerField(default=1)),
                ("weight", models.IntegerField(default=0)),
                ("sign", models.CharField(blank=True, max_length=350, null=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="veterinary.animal",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="veterinary.request",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
