# Generated by Django 4.2.20 on 2025-03-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0015_alter_rancher_veterinarians"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rancher",
            name="veterinarians",
            field=models.ManyToManyField(
                blank=True, related_name="ranchers", to="veterinary.veterinarian"
            ),
        ),
    ]
