# Generated by Django 4.2.20 on 2025-03-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0016_alter_rancher_veterinarians"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rancher",
            name="image",
        ),
        migrations.RemoveField(
            model_name="veterinarian",
            name="image",
        ),
    ]
