# Generated by Django 4.2.20 on 2025-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0017_remove_rancher_image_remove_veterinarian_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="slug",
            field=models.SlugField(default="test"),
            preserve_default=False,
        ),
    ]
