# Generated by Django 4.2.20 on 2025-03-25 19:25

from django.db import migrations, models
import veterinary.models.request_models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0018_veterinarian_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=veterinary.models.request_models.request_image_file_path,
            ),
        ),
    ]
