# Generated by Django 4.2.20 on 2025-03-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0019_request_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestImage",
        ),
    ]
