# Generated by Django 4.2.20 on 2025-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0020_delete_requestimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="code",
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="veterinarian",
            name="state",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Confirmed"), ("R", "Rejected")],
                default="P",
                max_length=1,
            ),
        ),
    ]
