# Generated by Django 4.2.20 on 2025-03-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0021_veterinarian_code_alter_veterinarian_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animalrequest",
            name="sign",
        ),
        migrations.RemoveField(
            model_name="animalrequest",
            name="weight",
        ),
    ]
