# Generated by Django 4.2.20 on 2025-03-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0023_request_tracking_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="latitude",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="longitude",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
