# Generated by Django 4.2.20 on 2025-04-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("veterinary", "0024_request_latitude_request_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="state",
            field=models.CharField(
                choices=[("N", "New"), ("C", "Confirm"), ("R", "Reject")],
                default="N",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="gallery.gallery",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
    ]
