# Generated by Django 4.2.20 on 2025-04-04 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0025_request_state_alter_animal_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteVeterinarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rancher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veterinary.rancher",
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veterinary.veterinarian",
                    ),
                ),
            ],
            options={
                "unique_together": {("rancher", "veterinarian")},
            },
        ),
        migrations.AddField(
            model_name="rancher",
            name="favorite_veterinarians",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                through="veterinary.FavoriteVeterinarian",
                to="veterinary.veterinarian",
            ),
        ),
    ]
