# Generated by Django 4.2.20 on 2025-04-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0026_favoriteveterinarian_rancher_favorite_veterinarians"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="request",
            name="state",
            field=models.CharField(
                choices=[
                    ("N", "New"),
                    ("C", "Confirm"),
                    ("R", "Reject"),
                    ("D", "Done"),
                ],
                default="N",
                max_length=2,
            ),
        ),
    ]
