# Generated by Django 4.2.20 on 2025-05-10 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import veterinary.models.medicine_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("veterinary", "0028_request_analysis_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="type",
            field=models.CharField(
                choices=[
                    ("T", "Tell"),
                    ("S", "SMS"),
                    ("IP", "In-Person"),
                    ("AI", "AI"),
                ],
                default="IP",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="veterinarian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="requests",
                to="veterinary.veterinarian",
            ),
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=veterinary.models.medicine_models.request_image_file_path,
                    ),
                ),
                ("analysis_result", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
